// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wilgysef.Stalk.EntityFrameworkCore;

#nullable disable

namespace Wilgysef.Stalk.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(StalkDbContext))]
    partial class StalkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Wilgysef.Stalk.Core.BackgroundJobs.BackgroundJob", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("Abandoned")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("JobArgs")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("JobArgsName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MaximumLifetime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NextRun")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BackgroundJobs");
                });

            modelBuilder.Entity("Wilgysef.Stalk.Core.Models.Jobs.Job", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DelayedUntil")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Finished")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Started")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Wilgysef.Stalk.Core.Models.JobTasks.JobTask", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DelayedUntil")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Finished")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ItemData")
                        .HasColumnType("longtext");

                    b.Property<string>("ItemId")
                        .HasColumnType("longtext");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<long?>("ParentTaskId")
                        .HasColumnType("bigint");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Started")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("ParentTaskId");

                    b.ToTable("JobTasks");
                });

            modelBuilder.Entity("Wilgysef.Stalk.Core.Models.JobTasks.JobTask", b =>
                {
                    b.HasOne("Wilgysef.Stalk.Core.Models.Jobs.Job", "Job")
                        .WithMany("Tasks")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wilgysef.Stalk.Core.Models.JobTasks.JobTask", "ParentTask")
                        .WithMany()
                        .HasForeignKey("ParentTaskId");

                    b.OwnsOne("Wilgysef.Stalk.Core.Models.JobTasks.JobTaskResult", "Result", b1 =>
                        {
                            b1.Property<long>("JobTaskId")
                                .HasColumnType("bigint");

                            b1.Property<string>("ErrorCode")
                                .HasColumnType("longtext");

                            b1.Property<string>("ErrorDetail")
                                .HasColumnType("longtext");

                            b1.Property<string>("ErrorMessage")
                                .HasColumnType("longtext");

                            b1.Property<bool?>("Success")
                                .HasColumnType("tinyint(1)");

                            b1.HasKey("JobTaskId");

                            b1.ToTable("JobTasks");

                            b1.WithOwner()
                                .HasForeignKey("JobTaskId");
                        });

                    b.Navigation("Job");

                    b.Navigation("ParentTask");

                    b.Navigation("Result")
                        .IsRequired();
                });

            modelBuilder.Entity("Wilgysef.Stalk.Core.Models.Jobs.Job", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
